# Create org, bucket & token by navigating to your influx url from browser
influx:
  url: http://localhost:8086  # location of influxdb v2 database
  bucket: Environment         # name of available bucket
  token: super-secret-token   # token with write permission to bucket
  org: "your org in influx"   # org of the bucket
  measurement: "weather"      # name to give to measurements

main:
  logverbosity: INFO # by increasing level of verbosity: FATAL, ERROR, WARNING, INFO, DEBUG
  loop_seconds: 420  # how long to wait before pulling data again from the device. 0 to only read once
  
weewx:
  db: "/var/lib/weewx/weewx.sdb"  # path to weex database file
  max_hours: 720                  # max amount of historical data to import

